# -*- coffee -*- -p
author: 'YC <yinso.chen@gmail.com>'
name: 'easydbi-sqlite'
description: 'Sqlite binding for EASYDBI'
version: '0.1.0'
repository:
  type: 'git'
  url: 'git://github.com/yinso/easydbi-sqlite.git'
main: './lib/main'
engines:
  node: '>= 0.8.4'
license: MIT        
scripts:
  test: 'make test'
  prepublish: 'make'
dependencies:
  coffee-script: '=1.8.0'
  underscore: '=1.7.0'
  node-uuid: '=1.4.1'
  sqlite3: '^3.1.0'
  async: '=0.9.0'
  loglet: '>=0.1.1'
  bluebird: '=2.10.0'
  fs.extra: '=1.3.2'
  easydbi: '>=0.2.4'
devDependencies:
  testlet: '>= 0.2.0'
  'coffee-bean': '>=0.3.0'
  
